USE `taikun`;
SELECT DATABASE() AS DatabaseSelezionato,
       CASE WHEN DATABASE()='taikun' THEN 'OK' ELSE 'STOP' END AS EsitoDatabase;
SELECT ROUTINE_NAME, ROUTINE_TYPE,
       CASE WHEN SHA2(ROUTINE_DEFINITION,256)='6d50508d402d4f35e5a8918825a5e6b66b5cfdcf5e4cf5fc41697b5535b6af23' THEN 'OK' ELSE 'STOP' END AS Fingerprint,
       CASE WHEN ROUTINE_DEFINITION LIKE '%MagazziniId=1%' THEN 'OK' ELSE 'STOP' END AS Warehouse1,
       CASE WHEN ROUTINE_DEFINITION LIKE '%DECIMAL(15,8)%' THEN 'OK' ELSE 'STOP' END AS QuantityScale,
       CASE WHEN ROUTINE_DEFINITION LIKE '%Giacenza%Impegnata%' THEN 'OK' ELSE 'STOP' END AS AvailabilityFormula,
       CASE WHEN ROUTINE_DEFINITION LIKE '%GROUP BY ArticoliId, TCId%' AND ROUTINE_DEFINITION LIKE '%ORDER BY ArticoliId, TCId%' THEN 'OK' ELSE 'STOP' END AS AggregateAndOrder,
       CASE WHEN ROUTINE_DEFINITION LIKE '%ORDER_INVENTORY_UNAVAILABLE%' AND ROUTINE_DEFINITION LIKE '%ORDER_INVENTORY_INVALID%' THEN 'OK' ELSE 'STOP' END AS StableSignals,
       CASE WHEN ROUTINE_DEFINITION NOT LIKE '%COMMIT%' AND ROUTINE_DEFINITION NOT LIKE '%ROLLBACK%' AND ROUTINE_DEFINITION NOT LIKE '%START TRANSACTION%' AND ROUTINE_DEFINITION NOT LIKE '%AUTOCOMMIT%' THEN 'OK' ELSE 'STOP' END AS NoAutonomousTransaction,
       SECURITY_TYPE,
       SQL_MODE,
       CHARACTER_SET_CLIENT,
       COLLATION_CONNECTION,
       DATABASE_COLLATION,
       ROUTINE_COMMENT,
       SHA2(DEFINER,256) AS DefinerSha256
FROM information_schema.routines
WHERE ROUTINE_SCHEMA='taikun' AND ROUTINE_NAME='Carrello_Documento';
SELECT CASE WHEN COUNT(*)=1 THEN 'OK' ELSE 'STOP' END AS CanonicalRoutineCount
FROM information_schema.routines
WHERE ROUTINE_SCHEMA='taikun' AND ROUTINE_NAME='Carrello_Documento';
SELECT SPECIFIC_NAME AS ROUTINE_NAME, ORDINAL_POSITION, PARAMETER_MODE, PARAMETER_NAME, DTD_IDENTIFIER
FROM information_schema.parameters
WHERE SPECIFIC_SCHEMA='taikun' AND SPECIFIC_NAME='Carrello_Documento'
ORDER BY ORDINAL_POSITION;
SELECT CASE WHEN COUNT(*)=19 THEN 'OK' ELSE 'STOP' END AS SignatureParameterCount
FROM information_schema.parameters
WHERE SPECIFIC_SCHEMA='taikun' AND SPECIFIC_NAME='Carrello_Documento';
SELECT CASE WHEN EXISTS (
  SELECT 1 FROM tipodocumenti WHERE Web=1 AND ImpegnaQnt=1
) THEN 'OK' ELSE 'STOP' END AS WebDocumentContract;
SELECT COUNT(*) AS NullTcIdRows FROM articoli_giacenze WHERE TCId IS NULL;
SELECT CASE WHEN EXISTS (
  SELECT 1 FROM information_schema.statistics
  WHERE TABLE_SCHEMA='taikun' AND TABLE_NAME='articoli_giacenze'
    AND NON_UNIQUE=0 AND COLUMN_NAME IN ('MagazziniId','ArticoliId','TCId')
  GROUP BY INDEX_NAME HAVING COUNT(DISTINCT COLUMN_NAME)=3
) THEN 'OK' ELSE 'STOP' END AS WarehouseArticleTcIndex;
SELECT CASE WHEN COUNT(*)=0 THEN 'OK' ELSE 'STOP' END AS AlternativeRoutines
FROM information_schema.routines
WHERE ROUTINE_SCHEMA='taikun' AND ROUTINE_NAME IN ('Carrello_Documento_WebV1','Carrello_Documento_InventoryV1');
