USE `taikun`;
SELECT DATABASE() AS DatabaseSelezionato,
       CASE WHEN DATABASE()='taikun' THEN 'OK' ELSE 'STOP' END AS EsitoDatabase;
SELECT CASE WHEN COUNT(*)=1 AND SUM(CASE WHEN SHA2(ROUTINE_DEFINITION,256)='__KEEPSTORE_NEW_FINGERPRINT__' THEN 1 ELSE 0 END)=1
       THEN 'OK' ELSE 'STOP' END AS CurrentNewFingerprint
FROM information_schema.routines
WHERE ROUTINE_SCHEMA='taikun' AND ROUTINE_NAME='Carrello_Documento';
SELECT CASE WHEN COUNT(*)=19 THEN 'OK' ELSE 'STOP' END AS SignatureParameterCount
FROM information_schema.parameters
WHERE SPECIFIC_SCHEMA='taikun' AND SPECIFIC_NAME='Carrello_Documento';
SELECT SECURITY_TYPE, SQL_MODE, CHARACTER_SET_CLIENT, COLLATION_CONNECTION, DATABASE_COLLATION, ROUTINE_COMMENT,
       CASE WHEN SQL_MODE='NO_AUTO_VALUE_ON_ZERO' THEN 'OK' ELSE 'STOP' END AS SqlMode,
       SHA2(DEFINER,256) AS DefinerSha256
FROM information_schema.routines
WHERE ROUTINE_SCHEMA='taikun' AND ROUTINE_NAME='Carrello_Documento';
