-- SEO-DISCOVERY-CONFIG-SCHEMA-1A / MySQL 8.0.42.
-- Eseguire solo sul database esplicitamente selezionato e autorizzato dal Product Owner.
-- Richiede preflight interamente OK. Non eseguire automaticamente in questo task.
-- CREATE senza IF NOT EXISTS: una tabella preesistente arresta l'installazione.
-- Nessuna credenziale reale, nessuna migrazione dei quattro campi legacy.

CREATE TABLE `aziende_seo` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AziendeId` INT NOT NULL,
  `ConfigVersion` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `RobotsMode` VARCHAR(32) NOT NULL DEFAULT '',
  `LinguaDefault` VARCHAR(16) NOT NULL DEFAULT '',
  `PaeseDefault` CHAR(2) NOT NULL DEFAULT '',
  `ValutaDefault` CHAR(3) NOT NULL DEFAULT '',
  `HomeTitleOverride` TEXT NOT NULL DEFAULT (''),
  `HomeMetaDescriptionOverride` TEXT NOT NULL DEFAULT (''),
  `SocialImageOverride` TEXT NOT NULL DEFAULT (''),
  `IndexNowEnabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `IndexNowKey` VARCHAR(128) NOT NULL DEFAULT '',
  `IndexNowKeyLocation` TEXT NOT NULL DEFAULT (''),

  `GoogleSearchConsoleProperty` VARCHAR(255) NOT NULL DEFAULT '',
  `GoogleSiteVerificationMethod` VARCHAR(32) NOT NULL DEFAULT '',
  `GoogleSiteVerificationToken` TEXT NOT NULL DEFAULT (''),
  `GoogleCloudProjectId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleOAuthClientId` VARCHAR(255) NOT NULL DEFAULT '',
  `GoogleOAuthClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `GoogleOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `GoogleOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `GoogleOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `GoogleOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `GoogleOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `GoogleOAuthRedirectUri` TEXT NOT NULL DEFAULT (''),
  `GoogleServiceAccountEmail` VARCHAR(255) NOT NULL DEFAULT '',
  `GoogleServiceAccountPrivateJsonEnc` LONGTEXT NOT NULL DEFAULT (''),
  `GoogleMerchantId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleMerchantProductDataSourceId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleMerchantPromotionDataSourceId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleMerchantProductReviewDataSourceId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleMerchantMerchantReviewDataSourceId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAnalyticsAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAnalyticsPropertyId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAnalyticsWebDataStreamId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAnalyticsMeasurementId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAnalyticsMeasurementProtocolSecretEnc` TEXT NOT NULL DEFAULT (''),
  `GoogleTagManagerAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleTagManagerContainerId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleTagManagerPublicId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAdsCustomerId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAdsManagerCustomerId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAdsConversionActionId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAdsConversionId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleAdsConversionLabel` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleBusinessProfileAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleBusinessProfileLocationId` VARCHAR(128) NOT NULL DEFAULT '',
  `GoogleBusinessProfilePlaceId` VARCHAR(128) NOT NULL DEFAULT '',
  `YouTubeChannelId` VARCHAR(128) NOT NULL DEFAULT '',

  `BingWebmasterSiteUrl` TEXT NOT NULL DEFAULT (''),
  `BingWebmasterVerificationMethod` VARCHAR(32) NOT NULL DEFAULT '',
  `BingWebmasterVerificationToken` TEXT NOT NULL DEFAULT (''),
  `BingWebmasterApiKeyEnc` TEXT NOT NULL DEFAULT (''),
  `BingOAuthClientId` VARCHAR(255) NOT NULL DEFAULT '',
  `BingOAuthClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `BingOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `BingOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `BingOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `BingOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `BingOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `BingOAuthRedirectUri` TEXT NOT NULL DEFAULT (''),
  `MicrosoftClarityProjectId` VARCHAR(128) NOT NULL DEFAULT '',

  `MetaBusinessId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaAppSecretEnc` TEXT NOT NULL DEFAULT (''),
  `MetaSystemUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaSystemUserAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `MetaSystemUserAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `MetaSystemUserScopes` TEXT NOT NULL DEFAULT (''),
  `MetaAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaDatasetId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `FacebookPageId` VARCHAR(128) NOT NULL DEFAULT '',
  `FacebookPageAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `InstagramBusinessAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `InstagramAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `InstagramAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `InstagramScopes` TEXT NOT NULL DEFAULT (''),
  `ThreadsUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `ThreadsAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `ThreadsAppSecretEnc` TEXT NOT NULL DEFAULT (''),
  `ThreadsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `ThreadsAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `ThreadsScopes` TEXT NOT NULL DEFAULT (''),
  `WhatsAppBusinessAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `WhatsAppPhoneNumberId` VARCHAR(128) NOT NULL DEFAULT '',
  `WhatsAppAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `WhatsAppAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',

  `TikTokSocialClientKey` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokSocialClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialOpenId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokSocialAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokSocialRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokSocialRedirectUri` TEXT NOT NULL DEFAULT (''),
  `TikTokMerchantClientKey` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokMerchantClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokMerchantId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokMerchantShopId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokMerchantShopCipher` VARCHAR(255) NOT NULL DEFAULT '',
  `TikTokMerchantAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokMerchantRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokMerchantScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokMerchantAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokMerchantRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokShopAppKey` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokShopAppSecretEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokShopShopCipher` VARCHAR(255) NOT NULL DEFAULT '',
  `TikTokShopAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokShopRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokShopScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokShopAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokShopRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokAdsBusinessCenterId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsAdvertiserId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokAdsScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokAdsAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokEventsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),

  `PinterestAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestRedirectUri` TEXT NOT NULL DEFAULT (''),
  `PinterestScopes` TEXT NOT NULL DEFAULT (''),
  `PinterestAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `PinterestRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `PinterestAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestTagId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestConversionTokenEnc` TEXT NOT NULL DEFAULT (''),

  `LinkedInOrganizationId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `LinkedInOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `LinkedInInsightTagId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInConversionRuleId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInConversionDirectTokenEnc` TEXT NOT NULL DEFAULT (''),

  `XUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `XClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `XClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XApiKey` VARCHAR(128) NOT NULL DEFAULT '',
  `XApiSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XAppBearerTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2AccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2RefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2Scopes` TEXT NOT NULL DEFAULT (''),
  `XOAuth2AccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `XOAuth2RefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `XOAuth1AccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth1AccessTokenSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XAdsAccountId` VARCHAR(128) NOT NULL DEFAULT '',

  `SnapOrganizationId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `SnapOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `SnapConversionsTokenEnc` TEXT NOT NULL DEFAULT (''),

  `FacebookUrl` TEXT NOT NULL DEFAULT (''),
  `InstagramUrl` TEXT NOT NULL DEFAULT (''),
  `ThreadsUrl` TEXT NOT NULL DEFAULT (''),
  `TikTokUrl` TEXT NOT NULL DEFAULT (''),
  `YouTubeUrl` TEXT NOT NULL DEFAULT (''),
  `LinkedInUrl` TEXT NOT NULL DEFAULT (''),
  `PinterestUrl` TEXT NOT NULL DEFAULT (''),
  `XUrl` TEXT NOT NULL DEFAULT (''),
  `SnapchatUrl` TEXT NOT NULL DEFAULT (''),
  `WhatsAppUrl` TEXT NOT NULL DEFAULT (''),
  `TelegramUrl` TEXT NOT NULL DEFAULT (''),
  `TrackingScriptLegacy` TEXT NOT NULL DEFAULT (''),
  `AltriSocialJson` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  `ExtraProviderConfigJson` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  `SecretsCryptoVersion` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `SecretsKeyId` VARCHAR(128) NOT NULL DEFAULT '',
  `DataCreazione` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DataModifica` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UtentiIdModifica` INT NOT NULL DEFAULT 0,
  `NoteInterne` TEXT NOT NULL DEFAULT (''),
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uq_aziende_seo_aziende` (`AziendeId`)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

-- Solo righe vuote/default: non migra automaticamente alcun valore legacy.
INSERT INTO `aziende_seo` (`AziendeId`)
SELECT `id` FROM `aziende`;
