'------------------------------------------------------------------------------
' <auto-generated>
'     KeepStore - carrello.aspx.designer.vb (manual for Web Site precompile)
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Imports System
Imports System.Web.UI
Imports System.Web.UI.HtmlControls
Imports System.Web.UI.WebControls

Partial Public Class carrello

    ' Panels / wrappers
    Protected WithEvents pnlFatturazione As Panel
    Protected WithEvents PnlSpedizione As Panel

    ' Repeaters / lists
    Protected WithEvents Repeater1 As Repeater

    ' GridViews (legacy)
    Protected WithEvents gvArticoliGratis As GridView
    Protected WithEvents gvVettori As GridView
    Protected WithEvents gvPagamento As GridView
    Protected WithEvents gvVettoriPromo As GridView

    ' Checkout UI
    Protected WithEvents LstScegliIndirizzo As DropDownList
    Protected WithEvents Checkout_Err As HtmlGenericControl
    Protected WithEvents litCheckoutErr As Literal

    ' Misc UI
    Protected WithEvents canorder As HtmlGenericControl
    Protected WithEvents tbShopIdGestPay As TextBox
    Protected WithEvents lblBuonoScontoIVA As Label

    ' Destination form
    Protected WithEvents ddlCitta2 As DropDownList
    Protected WithEvents tbTelefono2 As TextBox
    Protected WithEvents RFTelefono2 As RequiredFieldValidator

    ' Anchors / hidden
    Protected WithEvents open1 As HtmlAnchor
    Protected WithEvents open2 As HtmlAnchor
    Protected WithEvents insOmod As HtmlInputHidden

    ' Shipping summary labels
    Protected WithEvents lblTab_RagioneSocialeSpedizione As Label
    Protected WithEvents lblTab_NomeSpedizione As Label
    Protected WithEvents lblTab_IndirizzoSpedizione As Label
    Protected WithEvents lblTab_CittaSpedizione As Label
    Protected WithEvents lblTab_CapSpedizione As Label
    Protected WithEvents lblTab_ProvinciaSpedizione As Label
    Protected WithEvents lblTab_ZonaSpedizione As Label
    Protected WithEvents lblTab_TelSpedizione As Label
    Protected WithEvents lblTab_NotaDestinazione As Label

End Class
