'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Manual designer file added to stabilize compilation on server where .designer.vb may be missing.
'     It declares the server controls referenced by carrello.aspx.vb.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class carrello

    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater
    Protected WithEvents gvArticoliGratis As Global.System.Web.UI.WebControls.Repeater

    Protected WithEvents gvVettori As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents gvPagamento As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents gvVettoriPromo As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents rbSpedizioneGratis As Global.System.Web.UI.WebControls.RadioButton

    Protected WithEvents ImgBtnDestinazioneSi As Global.System.Web.UI.WebControls.ImageButton
    Protected WithEvents ImgBtnDestinazioneNo As Global.System.Web.UI.WebControls.ImageButton

    Protected WithEvents btnSalvaDest As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnModDest As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnElimDest As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btnAnnullaDest As Global.System.Web.UI.WebControls.Button

    Protected WithEvents LstScegliIndirizzo As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents LstDestinazione As Global.System.Web.UI.WebControls.DropDownList

    Protected WithEvents btSvuota As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btCompleta As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btContinua As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btAggiorna As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btSalvaPreventivo As Global.System.Web.UI.WebControls.Button
    Protected WithEvents btInviaOrdine As Global.System.Web.UI.WebControls.Button

    Protected WithEvents TB_BuonoSconto As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents GV_BuoniSconti As Global.System.Web.UI.WebControls.GridView
    Protected WithEvents LB_CancelBuonoSconto As Global.System.Web.UI.WebControls.LinkButton
    Protected WithEvents lblBuonoScontoIVA As Global.System.Web.UI.WebControls.Label

    Protected WithEvents Checkout_Err As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents litCheckoutErr As Global.System.Web.UI.WebControls.Literal

    Protected WithEvents pnlFatturazione As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents PnlSpedizione As Global.System.Web.UI.WebControls.Panel

    Protected WithEvents canorder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents tbShopIdGestPay As Global.System.Web.UI.WebControls.TextBox

    Protected WithEvents ddlCitta2 As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbTelefono2 As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents RFTelefono2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    Protected WithEvents open1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents open2 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents insOmod As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    ' Labels used in shipping summary tab
    Protected WithEvents lblTab_RagioneSocialeSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_NomeSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_IndirizzoSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_CittaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_CapSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_ProvinciaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_ZonaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_TelSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_NotaDestinazione As Global.System.Web.UI.WebControls.Label

End Class
