'------------------------------------------------------------------------------
' <auto-generated>
'     KeepStore - designer manuale per deployment "Web Site" (no csproj).
'
'     In alcuni deploy manca/allinea male il file .designer.vb: aspnet_compiler
'     fallisce con BC30451/BC30456. Questo file rende esplicite le dichiarazioni
'     dei controlli referenziati da carrello.aspx.vb.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Web.UI
Imports System.Web.UI.HtmlControls
Imports System.Web.UI.WebControls

Partial Public Class carrello

    '--- Pannelli legacy / wrapper ---
    Protected WithEvents pnlFatturazione As Global.System.Web.UI.WebControls.Panel
    Protected WithEvents PnlSpedizione As Global.System.Web.UI.WebControls.Panel

    '--- Lista prodotti carrello ---
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '--- Articoli omaggio / gratuiti ---
    Protected WithEvents gvArticoliGratis As Global.GridViewCompat

    '--- Checkout (indirizzi / spedizioni / pagamenti) ---
    Protected WithEvents LstScegliIndirizzo As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents gvVettori As Global.GridViewCompat
    Protected WithEvents gvPagamento As Global.GridViewCompat

    '--- Messaggi / blocchi UI ---
    Protected WithEvents canorder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents Checkout_Err As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents litCheckoutErr As Global.System.Web.UI.WebControls.Literal

    '--- Campi nascosti / appoggi ---
    Protected WithEvents tbShopIdGestPay As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents insOmod As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '--- Coupon / IVA ---
    Protected WithEvents lblBuonoScontoIVA As Global.System.Web.UI.WebControls.Label

    '--- Destinazione (form) ---
    Protected WithEvents ddlCitta2 As Global.System.Web.UI.WebControls.DropDownList
    Protected WithEvents tbTelefono2 As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents RFTelefono2 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '--- Anchor / popup ---
    Protected WithEvents open1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    Protected WithEvents open2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '--- Riepilogo spedizione (label) ---
    Protected WithEvents lblTab_RagioneSocialeSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_NomeSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_IndirizzoSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_CittaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_CapSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_ProvinciaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_ZonaSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_TelSpedizione As Global.System.Web.UI.WebControls.Label
    Protected WithEvents lblTab_NotaDestinazione As Global.System.Web.UI.WebControls.Label

End Class
