[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)][string[]]$DatabaseNames,
    [switch]$Apply,
    [switch]$ListCandidates,
    [string]$Server='127.0.0.1',
    [int]$Port=3306,
    [PSCredential]$Credential
)
$ErrorActionPreference='Stop'
$repo=Split-Path -Parent $PSScriptRoot
$dll=Join-Path $repo 'Bin\MySql.Data.dll'
$canonical=Join-Path $repo 'Database Taikun\Migrations\20260911_ORDER_INVENTORY_ATOMIC_RESERVATION_1A_forward.sql'
$newFingerprint='6d50508d402d4f35e5a8918825a5e6b66b5cfdcf5e4cf5fc41697b5535b6af23'
$excluded=@('mysql','sys','information_schema','performance_schema','connessioni','city_registry')
$required=@('carrello','articoli_giacenze','tipodocumenti','documenti','documentirighe','vcarrello')
function Open-Db([string]$db){$b=New-Object MySql.Data.MySqlClient.MySqlConnectionStringBuilder;$b.Server=$Server;$b.Port=$Port;$b.Database=$db;$b.UserID=$Credential.UserName;$b.Password=$Credential.GetNetworkCredential().Password;$b.SslMode=[MySql.Data.MySqlClient.MySqlSslMode]::None;$c=New-Object MySql.Data.MySqlClient.MySqlConnection($b.ConnectionString);$c.Open();$c}
function Scalar($c,[string]$sql){$x=$c.CreateCommand();$x.CommandText=$sql;try{$x.ExecuteScalar()}finally{$x.Dispose()}}
function Rows($c,[string]$sql){$x=$c.CreateCommand();$x.CommandText=$sql;$r=$x.ExecuteReader();try{$a=@();while($r.Read()){$o=[ordered]@{};for($i=0;$i -lt $r.FieldCount;$i++){$o[$r.GetName($i)]=$r.GetValue($i)};$a+=[pscustomobject]$o};$a}finally{$r.Dispose();$x.Dispose()}}
function Exec($c,[string]$sql){$x=$c.CreateCommand();$x.CommandText=$sql;try{[void]$x.ExecuteNonQuery()}finally{$x.Dispose()}}
function Discover($c){$out=@();foreach($row in (Rows $c 'SHOW DATABASES')){$db=[string]$row.Database;if($db -match '^[A-Za-z0-9_]+$' -and $db -notin $excluded){try{$rc=[int](Scalar $c "SELECT COUNT(*) FROM information_schema.routines WHERE ROUTINE_SCHEMA='$db' AND ROUTINE_NAME='Carrello_Documento' AND ROUTINE_TYPE='PROCEDURE'");$tc=[int](Scalar $c ("SELECT COUNT(*) FROM information_schema.tables WHERE TABLE_SCHEMA='$db' AND TABLE_NAME IN ('"+($required -join "','")+"')"));$pc=[int](Scalar $c "SELECT COUNT(*) FROM information_schema.parameters WHERE SPECIFIC_SCHEMA='$db' AND SPECIFIC_NAME='Carrello_Documento'");if($rc -eq 1 -and $tc -eq $required.Count -and $pc -eq 19){$out+=$db}}catch{}}};$out|Sort-Object}
if(-not(Test-Path $dll)){throw 'MySql.Data non disponibile'};Add-Type -Path $dll
if(-not $ListCandidates -and (-not $DatabaseNames -or $DatabaseNames.Count -eq 0)){Write-Output 'DATABASE_ALLOWLIST_REQUIRED';return}
if($DatabaseNames){$DatabaseNames=@($DatabaseNames|ForEach-Object{$_.Trim()});if(($DatabaseNames|Where-Object{[string]::IsNullOrWhiteSpace($_)}).Count -gt 0){throw 'nome database vuoto'};if(($DatabaseNames|Group-Object|Where-Object{$_.Count -gt 1}).Count -gt 0){throw 'database duplicato'};if(($DatabaseNames|Where-Object{$_ -notmatch '^[A-Za-z0-9_]+$' -or $_ -in $excluded}).Count -gt 0){throw 'nome database non consentito'}}
if(-not $Credential){$Credential=Get-Credential -Message 'Credenziale amministrativa MySQL locale (password nascosta)'}
$root=Open-Db 'information_schema';try{
 if($ListCandidates){Write-Output ('KEEPSTORE_CANDIDATES='+((Discover $root)-join ', '));return}
 $states=@();foreach($db in $DatabaseNames){$exists=[int](Scalar $root "SELECT COUNT(*) FROM information_schema.schemata WHERE SCHEMA_NAME='$db'");$rc=[int](Scalar $root "SELECT COUNT(*) FROM information_schema.routines WHERE ROUTINE_SCHEMA='$db' AND ROUTINE_NAME='Carrello_Documento' AND ROUTINE_TYPE='PROCEDURE'");$tc=[int](Scalar $root ("SELECT COUNT(*) FROM information_schema.tables WHERE TABLE_SCHEMA='$db' AND TABLE_NAME IN ('"+($required -join "','")+"')"));$pc=[int](Scalar $root "SELECT COUNT(*) FROM information_schema.parameters WHERE SPECIFIC_SCHEMA='$db' AND SPECIFIC_NAME='Carrello_Documento'");if($exists -ne 1 -or $rc -ne 1 -or $tc -ne $required.Count -or $pc -ne 19){throw "DATABASE_PREFLIGHT_FAILED:$db"};$states+=[pscustomobject]@{Database=$db;Preflight='OK';Apply='DRYRUN';Verify='NOT_RUN';Rollback='NOT_RUN'}}
 Write-Output ('AUTHORIZED_DATABASES='+($DatabaseNames -join ', '));Write-Output ('AUTHORIZED_COUNT='+$DatabaseNames.Count);$states|Format-Table -AutoSize
 if(-not $Apply){Write-Output 'MODE=DRYRUN';return};$confirm=Read-Host "Digitare APPLY $($DatabaseNames.Count) per confermare esattamente questi database";if($confirm -ne "APPLY $($DatabaseNames.Count)"){Write-Output 'APPLY_CANCELLED';return}
 $template=Get-Content -Raw $canonical;$m=[regex]::Match($template,'(?is)CREATE\s+DEFINER=__KEEPSTORE_HISTORICAL_DEFINER__\s+PROCEDURE[\s\S]*?END\s*\$\$');if(-not $m.Success){throw 'sorgente canonica non riconosciuta'};$createTemplate=$m.Value -replace '\$\$$','';$backupRoot="C:\Temp\KeepStore_MultiDb_Backups_$(Get-Date -Format yyyyMMdd_HHmmss)";New-Item -ItemType Directory -Path $backupRoot -Force|Out-Null
 foreach($state in $states){$db=$state.Database;$cn=$null;$backup=Join-Path $backupRoot ($db+'.sql');try{$cn=Open-Db $db;$show=$cn.CreateCommand();$show.CommandText='SHOW CREATE PROCEDURE `'+$db+'`.`Carrello_Documento`';$rd=$show.ExecuteReader();try{if(-not $rd.Read()){throw 'SHOW CREATE vuoto'};$old=[string]$rd.GetValue(2)}finally{$rd.Dispose();$show.Dispose()};[IO.File]::WriteAllText($backup,$old,(New-Object Text.UTF8Encoding($false)));$fp=[string](Scalar $cn "SELECT SHA2(ROUTINE_DEFINITION,256) FROM information_schema.routines WHERE ROUTINE_SCHEMA='$db' AND ROUTINE_NAME='Carrello_Documento'");if($fp -eq $newFingerprint){$state.Apply='ALREADY_COMPLIANT';$state.Verify='OK';continue};$def=[regex]::Match($old,'(?i)^CREATE\s+DEFINER\s*=\s*([^\s]+)\s+PROCEDURE').Groups[1].Value;if([string]::IsNullOrWhiteSpace($def)){throw 'DEFINER non acquisito'};$create=$createTemplate.Replace('__KEEPSTORE_HISTORICAL_DEFINER__',$def);$create=[regex]::Replace($create,'(?i)(PROCEDURE\s+)(?:`[^`]+`\.)?`?Carrello_Documento`?','$1`'+$db+'`.`Carrello_Documento`');Exec $cn ('DROP PROCEDURE `'+$db+'`.`Carrello_Documento`');Exec $cn $create;$state.Apply='APPLIED';$after=[string](Scalar $cn "SELECT SHA2(ROUTINE_DEFINITION,256) FROM information_schema.routines WHERE ROUTINE_SCHEMA='$db' AND ROUTINE_NAME='Carrello_Documento'");if($after -ne $newFingerprint){throw 'verify fingerprint non conforme'};$state.Verify='OK'}catch{try{if($cn -and(Test-Path $backup)){Exec $cn ('DROP PROCEDURE `'+$db+'`.`Carrello_Documento`');$old=Get-Content -Raw $backup;Exec $cn $old;$state.Rollback='OK'}}catch{$state.Rollback='FAILED'};throw}finally{if($cn){$cn.Dispose()}}};$states|Format-Table -AutoSize
}finally{$root.Dispose();$Credential=$null}
