-- REV2 MODULAR-ARCHITECTURE-FREEZE / SOCIAL / MARKETING / MySQL 8.0.42.
-- DRAFT NON INSTALLATO E NON PRONTO AL ROLLOUT: non eseguire in questo task.
-- Richiede futuro gate MySQL/ambiente, preflight/verify read-only, backup e allowlist Product Owner.
-- Nessun USE, nome database cliente, seed, grant attivo o copia di valori legacy.
-- aziende_social 1:1 = profili pubblici e impostazioni generali; account provider 1:N.
-- Profili sameAs pubblici non richiedono licenza API. TrackingScriptLegacy non e eseguito da questo schema.
-- ProviderCode/AccountCode non vuoti e segregazione token per provider sono gate del futuro gestionale.
-- TikTok Merchant OAuth storico NON confluisce qui ne nel TikTok Shop Seller senza audit separato.

CREATE TABLE `aziende_social` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AziendeId` INT NOT NULL,
  `ConfigVersion` SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  `MicrosoftClarityProjectId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `FacebookUrl` TEXT NOT NULL DEFAULT (''),
  `InstagramUrl` TEXT NOT NULL DEFAULT (''),
  `ThreadsUrl` TEXT NOT NULL DEFAULT (''),
  `TikTokUrl` TEXT NOT NULL DEFAULT (''),
  `YouTubeUrl` TEXT NOT NULL DEFAULT (''),
  `LinkedInUrl` TEXT NOT NULL DEFAULT (''),
  `PinterestUrl` TEXT NOT NULL DEFAULT (''),
  `XUrl` TEXT NOT NULL DEFAULT (''),
  `SnapchatUrl` TEXT NOT NULL DEFAULT (''),
  `WhatsAppUrl` TEXT NOT NULL DEFAULT (''),
  `TelegramUrl` TEXT NOT NULL DEFAULT (''),
  `TrackingScriptLegacy` TEXT NOT NULL DEFAULT (''),
  `AltriSocialJson` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  `DataCreazione` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DataModifica` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UtentiIdModifica` INT NOT NULL DEFAULT 0,
  `NoteInterne` TEXT NOT NULL DEFAULT (''),
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uq_aziende_social_azienda` (`AziendeId`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE `aziende_social_account` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `AziendeId` INT NOT NULL,
  `ProviderCode` VARCHAR(32) NOT NULL DEFAULT '',
  `AccountCode` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaBusinessId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaAppSecretEnc` TEXT NOT NULL DEFAULT (''),
  `MetaSystemUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaSystemUserAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `MetaSystemUserAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `MetaSystemUserScopes` TEXT NOT NULL DEFAULT (''),
  `MetaAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaDatasetId` VARCHAR(128) NOT NULL DEFAULT '',
  `MetaCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `FacebookPageId` VARCHAR(128) NOT NULL DEFAULT '',
  `FacebookPageAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `InstagramBusinessAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `InstagramAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `InstagramAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `InstagramScopes` TEXT NOT NULL DEFAULT (''),
  `ThreadsUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `ThreadsAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `ThreadsAppSecretEnc` TEXT NOT NULL DEFAULT (''),
  `ThreadsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `ThreadsAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `ThreadsScopes` TEXT NOT NULL DEFAULT (''),
  `WhatsAppBusinessAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `WhatsAppPhoneNumberId` VARCHAR(128) NOT NULL DEFAULT '',
  `WhatsAppAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `WhatsAppAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokSocialClientKey` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokSocialClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialOpenId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokSocialAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokSocialAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokSocialRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokSocialRedirectUri` TEXT NOT NULL DEFAULT (''),
  `TikTokAdsBusinessCenterId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsAdvertiserId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `TikTokAdsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `TikTokAdsScopes` TEXT NOT NULL DEFAULT (''),
  `TikTokAdsAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `TikTokEventsAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestAppId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestRedirectUri` TEXT NOT NULL DEFAULT (''),
  `PinterestScopes` TEXT NOT NULL DEFAULT (''),
  `PinterestAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `PinterestAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `PinterestRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `PinterestAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestCatalogId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestTagId` VARCHAR(128) NOT NULL DEFAULT '',
  `PinterestConversionTokenEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOrganizationId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `LinkedInOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `LinkedInOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `LinkedInInsightTagId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInConversionRuleId` VARCHAR(128) NOT NULL DEFAULT '',
  `LinkedInConversionDirectTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XUserId` VARCHAR(128) NOT NULL DEFAULT '',
  `XClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `XClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XApiKey` VARCHAR(128) NOT NULL DEFAULT '',
  `XApiSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XAppBearerTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2AccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2RefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth2Scopes` TEXT NOT NULL DEFAULT (''),
  `XOAuth2AccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `XOAuth2RefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `XOAuth1AccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `XOAuth1AccessTokenSecretEnc` TEXT NOT NULL DEFAULT (''),
  `XAdsAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapOrganizationId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapAdAccountId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapPixelId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapClientId` VARCHAR(128) NOT NULL DEFAULT '',
  `SnapClientSecretEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthAccessTokenEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthRefreshTokenEnc` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthScopes` TEXT NOT NULL DEFAULT (''),
  `SnapOAuthAccessTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `SnapOAuthRefreshTokenExpiresAt` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00',
  `SnapConversionsTokenEnc` TEXT NOT NULL DEFAULT (''),
  `SecretsCryptoVersion` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `SecretsKeyId` VARCHAR(128) NOT NULL DEFAULT '',
  `DataCreazione` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `DataModifica` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UtentiIdModifica` INT NOT NULL DEFAULT 0,
  `NoteInterne` TEXT NOT NULL DEFAULT (''),
  PRIMARY KEY (`Id`),
  UNIQUE KEY `uq_social_account` (`AziendeId`, `ProviderCode`, `AccountCode`)
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
